name: Build Multiple LaTeX Documents
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Compile the first LaTeX document
      - name: Compile TechDoc
        uses: xu-cheng/latex-action@v3
        with:
          root_file: TechDoc/TechDoc.tex
          work_in_root_file_dir: true

      # Compile the second LaTeX document
      - name: Compile UserManual
        uses: xu-cheng/latex-action@v3
        with:
          root_file: UserManual/UserMan.tex
          work_in_root_file_dir: true

      # Upload all PDFs as artifacts
      - name: Upload PDF files
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: |
            TechDoc/TechDoc.pdf
            UserManual/UserMan.pdf
      
      # Upload compiled pdfs
      - name: Commit and Push PDFs
        env: 
              GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"

              # Adding the remote using the provided token
              git remote set-url origin https://${GH_TOKEN}@github.com/Tersect-Browser/Portfolio-Docs.git
          
              git add TechDoc/TechDoc.pdf UserManual/UserMan.pdf
              git commit -m "Update compiled PDFs"
              git push origin main
